### ISSUE TITLE
Feature request: display total height

### ISSUE THREAD

**Issue by kloppertje** [foosel/OctoPrint-DisplayZ#1]
Would it be possible to not only show the current height, but also the total height? E.g. Current Height: 0.50mm of 13.4mm.

**Comment by OllisGit** [comment]
@kloppertje Maybe this Plugin fulfills your requirements (V1.3.0)

https://github.com/OllisGit/OctoPrint-DisplayLayerProgress

BR
Olli

**Comment by kouki31** [comment]
thanks for the link
