### ISSUE TITLE
Feature Request: show layer instead mm

### ISSUE THREAD

**Issue by ManuelW77** [foosel/OctoPrint-DisplayZ#2]
hey there,

maybe you can make it switchable to show what users want. mm or layer of layers.

**Comment by foosel** [comment]
No. OctoPrint doesn't know which layer it is on. It has a rough idea of the Z position, but to know which layer of how many that would actually correspond to it requires information that might not even be available at all at time of print (no file analysis done yet or printing from SD) and it still might be off.

If you now say, "ah, but the GCODE viewer does display me a layer number": that's purely within the GCODE viewer. No way to access that kind of data from this plugin, it gets its data from the backend instead.

**Comment by OllisGit** [comment]
@ManuelW77  Maybe this Plugin fulfills your requirements (V1.3.0)

https://github.com/OllisGit/OctoPrint-DisplayLayerProgress

BR
Olli
