### ISSUE TITLE
Not Displaying on the Prusa mk3

### ISSUE THREAD

**Issue by arne182** [foosel/OctoPrint-DisplayZ#3]
The height is not displayed and after installing there are constant disconnects.

**Comment by arne182** [comment]
This happens when printing from the SD Card.

**Comment by foosel** [comment]
> This happens when printing from the SD Card.

There's your problem. The plugin cannot show you height information that it doesn't know (as in, the command to increase height wasn't sent by OctoPrint).

> after installing there are constant disconnects.

Please open a separate ticket with `serial.log` and `octoprint.log` please.
