### ISSUE TITLE
Up for adoption, looking for a new maintainer

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint-DisplayZ#7]
I lack the time to give this plugin the attention it deserves (though seldomly needs) next to maintaining OctoPrint itself. I hereby declare it abandoned and officially put it up for adoption. If you want to take over maintenance, please comment here and we can work out a transfer.

**Comment by Sunoo** [comment]
I’d be willing to take over maintenance for this, as it’s one of the few plugins I always make sure to install. It really doesn’t seem like it requires too much watching though.

**Comment by foosel** [comment]
I've sent you a collaborator invite :)

**Comment by Sunoo** [comment]
Thanks, I accepted it. Should I strip off the “Abandoned” messaging then?

**Comment by foosel** [comment]
Yep, feel free to do that, delete the github workflow (`.github/workflows/close-issues.yml`) and close the ticket when done. I'll unmark it on the plugin repository.

Thanks for taking over!

**Comment by Sunoo** [comment]
No problem, happy to help where I can.

Looks like I don't have permissions to change the tags or description on the project though, so if you can remove the abandoned from those places as well, I'd appreciate it.

**Comment by foosel** [comment]
Done, and the plugin listing on the repo is also edited (page build is running)

**Comment by Sunoo** [comment]
Great, thanks!

**Comment by Sunoo** [comment]
If you have a second at some point, might be worth dropping “Provided as is, no support, no maintenance.” from the description too. Not a big deal though.
